"""Evaluate the rule baseline and the independent ML models against ground truth.

Trains on the first days of the dataset, then scores both models on the held-out test days:
- counterfactual impact on every scenario in the grid, on two unseen normal weekdays;
- transaction-level predictions over the whole test period, alongside the best achievable score
  (the true success probability).

Usage:
    python scripts/evaluate.py [--data DIR] [--out DIR] [--quick]
"""

import argparse
import json
import platform
import sys
import time
from pathlib import Path

import numpy as np
import sklearn

from backend.config import REPO_ROOT
from backend.data.io import load_dataset
from backend.evaluation.grid import scenario_grid
from backend.evaluation.harness import OUT_OF_RANGE_SHARE, SUPPORT_QUANTILES, Support, run_grid
from backend.evaluation.scoring import TARGETS, summarize_errors, transaction_scores
from backend.models.independent import IndependentModels
from backend.models.rule_baseline import RuleBaseline
from backend.models.splits import evaluation_windows, first_attempts_on, time_split
from backend.simulation.interventions import observe
from backend.simulation.metrics import Predictions
from backend.simulation.oracle import true_success_probability

DEFAULT_DATA = REPO_ROOT / "data" / "generated" / "default"
DEFAULT_OUT = REPO_ROOT / "experiments" / "harness"


def _log(message: str) -> None:
    print(message, flush=True)


def _fmt(value, digits: int = 3) -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "–"
    return f"{value:,.{digits}f}"


def _markdown(summary: dict) -> str:
    lines = [
        "# Evaluation harness results",
        "",
        "Synthetic data; simulation output, not real payment performance. Generated by "
        "`python scripts/evaluate.py`.",
        "",
        f"- Train days: {summary['split']['train'][0]} to {summary['split']['train'][-1]}",
        f"- Test days: {summary['split']['test'][0]} to {summary['split']['test'][-1]}",
        f"- Counterfactual windows: {', '.join(summary['windows'])}",
        f"- Scenarios: {summary['n_scenarios']} per window "
        f"({summary['range_counts'].get('in_range', 0)} in range, "
        f"{summary['range_counts'].get('out_of_range', 0)} out of range, over both windows)",
        f"- Out of range: more than {OUT_OF_RANGE_SHARE:.0%} of affected transactions have "
        f"a state feature outside the training {SUPPORT_QUANTILES[0]:.1%}–"
        f"{SUPPORT_QUANTILES[1]:.1%} range",
        "",
        "## Counterfactual error by range",
        "",
        "MAE with a 95% bootstrap interval. Relative error and sign accuracy only count "
        "scenarios whose true effect is material.",
        "",
        "| Target | Range | Predictor | n | MAE [95% CI] | RMSE | Median rel. error | Sign acc. |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in summary["by_range"]:
        lines.append(
            f"| {row['target']} | {row['range']} | {row['predictor']} | {row['n']} | "
            f"{_fmt(row['mae'])} [{_fmt(row['mae_ci_low'])}, {_fmt(row['mae_ci_high'])}] | "
            f"{_fmt(row['rmse'])} | {_fmt(row['median_relative_error'])} | "
            f"{_fmt(row['sign_accuracy'], 2)} |"
        )
    lines += [
        "",
        "## Success-rate error by scenario type (pp)",
        "",
        "| Type | Predictor | n | MAE [95% CI] | Median rel. error | Sign acc. |",
        "|---|---|---|---|---|---|",
    ]
    for row in summary["by_type"]:
        if row["target"] != "success_rate_delta_pp":
            continue
        lines.append(
            f"| {row['type']} | {row['predictor']} | {row['n']} | "
            f"{_fmt(row['mae'])} [{_fmt(row['mae_ci_low'])}, {_fmt(row['mae_ci_high'])}] | "
            f"{_fmt(row['median_relative_error'])} | {_fmt(row['sign_accuracy'], 2)} |"
        )
    lines += [
        "",
        "## Transaction-level predictions on the test period",
        "",
        "`true_probability` is the data-generating process's own success probability: the best "
        "any model could do.",
        "",
        "| Predictor | AUC | Brier | Log loss | Mean p / observed | Reason log loss | "
        "Latency log-MAE |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, s in summary["transaction_level"].items():
        lines.append(
            f"| {name} | {_fmt(s['auc'], 4)} | {_fmt(s['brier'], 5)} | {_fmt(s['log_loss'], 4)} | "
            f"{_fmt(s['mean_predicted'], 4)} / {_fmt(s['mean_observed'], 4)} | "
            f"{_fmt(s.get('reason_log_loss'))} | {_fmt(s.get('latency_log_mae'))} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--quick", action="store_true", help="Every 6th scenario and one window, for a smoke run."
    )
    args = parser.parse_args()
    if not (args.data / "manifest.json").exists():
        raise SystemExit(f"No dataset at {args.data}; run scripts/generate_data.py first.")

    started = time.perf_counter()
    dataset = load_dataset(args.data)
    split = time_split(dataset)
    windows = evaluation_windows(dataset, split)
    grid = scenario_grid()
    if args.quick:
        windows, grid = windows[:1], grid[::6]
    train = first_attempts_on(dataset, split.train_days)
    test = first_attempts_on(dataset, split.test_days)

    _log(
        f"Fitting on {len(train):,} first attempts ({split.train_days[0]}..{split.train_days[-1]})"
    )
    rules = RuleBaseline.fit(train)
    independent = IndependentModels.fit(
        train, dataset.customers, dataset.merchants, dataset.config.seed
    )
    predictors = [rules, independent]

    _log(f"Scoring {len(test):,} test-period first attempts")
    success = (test["transaction_status"] == "SUCCESS").to_numpy()
    latency = test["latency_ms"].to_numpy().astype(float)
    reasons = test["failure_reason"].cat.codes.to_numpy()
    transaction_level = {
        p.name: transaction_scores(success, latency, reasons, p.predict(test)) for p in predictors
    }
    true_p = true_success_probability(dataset).loc[test["transaction_id"]].to_numpy()
    reference = Predictions(
        p_success=true_p,
        reason_probs=np.full((len(test), 9), 1 / 9),
        latency_median_ms=latency,
        latency_log_sigma=np.zeros(len(test)),
    )
    scores = transaction_scores(success, latency, reasons, reference)
    transaction_level["true_probability"] = {
        k: v for k, v in scores.items() if not k.startswith(("reason", "latency"))
    }

    _log(f"Running {len(grid)} scenarios x {len(windows)} windows")
    observed = observe(dataset)
    results = run_grid(
        dataset, observed, windows, predictors, grid, Support.from_training(train), progress=_log
    )

    by_range = summarize_errors(results, ["target", "range", "predictor"])
    by_type = summarize_errors(results, ["target", "type", "predictor"])
    scenario_rows = results.drop_duplicates(["scenario", "window"])
    summary = {
        "data": dataset.config.model_dump(mode="json"),
        "split": {
            "train": [d.isoformat() for d in split.train_days],
            "test": [d.isoformat() for d in split.test_days],
        },
        "windows": [w.isoformat() for w in windows],
        "n_scenarios": len(grid),
        "range_counts": scenario_rows["range"].value_counts().to_dict(),
        "targets": list(TARGETS),
        "by_range": by_range.to_dict(orient="records"),
        "by_type": by_type.to_dict(orient="records"),
        "transaction_level": transaction_level,
        "environment": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "scikit_learn": sklearn.__version__,
        },
        "quick": args.quick,
    }

    args.out.mkdir(parents=True, exist_ok=True)
    results.to_csv(args.out / "scenario_results.csv", index=False)
    (args.out / "results.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    (args.out / "results.md").write_text(_markdown(summary), encoding="utf-8")
    _log(f"Wrote {args.out} in {time.perf_counter() - started:.0f}s")


if __name__ == "__main__":
    main()
